* Types of questions

Current questiontypes
Yes, No, N.a. √
Yes, No, N.a. + Value - Date √
Yes, No, N.a. + Value - Text √
Yes, No, N.a. + Value - Photo √
Yes, No, N.a. + Value - List - single answer √

New questiontypes
6. Yes, No, N.a. + Value - List - multiple answers
7. Yes, No, N.a. + Value - Currency
8. Yes, No, N.a. + Value - Number

Same as above but without yes/no/nvt buttons
9. Date
10. Text
11. List
12. Currency
13. Number

- The values of question types with an open value are of a specific type, depending on
question type
- Validate input for question type (valuta (€ 350, $10.10, AUD1000), number ) in ember ui
- Also keep locale in mind (10,001.01 and 10.001,01)
- Every answer in a multiple answer list should show up in dashboard as a separate answer
So either dashboard splits answers for analysis, or checklist can create hidden
answers perhaps, and log two separate answers for the multiple choice list
question, but user only sees one, the collated answer

Proposal is to use a boolean in tent for the list question type whether multiple
answers are possible, and one more field to indicate the type of the open value.

Also make value input field more noticable as such (box around it for example)

For future consideration:

A value can also be the result of a search of an external database.
But api's are not stable perhaps, so user/group should be able to attach script
to query api, so a wrapper for the api. 
Maybe a questiontype per database or group of databases.
External database such as kentekens, certificaties, asbest, bodem saneerders,
koelinstallatie monteurs
For closed databases user has to enter authentication perhaps, or route call to 
server who has authentication perhaps


To 
